### ISSUE TITLE
Finnes det kodeverk for å få frem relasjon mellom pasienter?

### ISSUE THREAD

**Issue by micer2004** [HL7Norway/basisprofiler-r3#10]
Finnes det mulighet til å definere at det er "far"/"mor"/"datter"-relasjon mellom de person-objekter osv.?

**Comment by thomiz** [comment]
Ja, gjennom bruk av ressursene RelatedPerson og Person kan du få til å modellere familieforhold i ganske detaljert form. @micer2004  kanskje du kan sette opp noen eksempler på hvordan dette kan benyttes, med use-case for hvor dette er relevant? 

Slik det er nå forholder vi oss bare til Patient ressursene i de use-casene jeg kjenner til, eventuelt med kontaktinformasjon.

**Comment by rockphotog** [comment]
Note to self:

https://www.hl7.org/fhir/valueset-relatedperson-relationshiptype.html

**Comment by thomiz** [comment]
Er dette en aksjon @rockphotog? Jeg lukker denne.

**Comment by rockphotog** [comment]
Ikke for basisprofiler, men for IG for grunndata/PREG.
