### ISSUE TITLE
Adresse: Hva med Volven-referanser til kommune, bydel, fylke?

### ISSUE THREAD

**Issue by micer2004** [HL7Norway/basisprofiler-r3#11]
Det finnes definisjon i Volven

3402 - Kommunenummer og regionale spesialkoder
3403 - Bydelsnummer
3404 - Fylker i Norge

Skal disse fases ut da?

**Comment by thomiz** [comment]
Nei, de skal ikke nødvendigvis fases ut, men master for fylke, kommune og bydelskodeverk ligger hos andre enn oss. Vi kan diskutere dette problemet litt videre på neste HL7 workshop tror jeg.

Kan dere få det på agendaen @rockphotog  @oaassv

**Comment by rockphotog** [comment]
Det er jo en interessant use case for HealthTerm sin forvaltning av administrative kodeverk som er forvaltet av andre: Kan de lage automatisk oppdatering fra andre kilder (som SSB), som inkluderer versjonering på ressursnivå? Eller skal man bare si at det er oppdaterte kodeverk som tilbys i APIet? Det er flere ting som tyder på at egen Terminology Server mellom konsument og HealthTerm innhenter dette selv fra tredjepart.

**Comment by thomiz** [comment]
Lukkes, HealthTerm håndteres separat. Foreløpig henviser vi til volven for kodeverk som er registrert der.
