### ISSUE TITLE
no-basis-Address CodeSystem mapping

### ISSUE THREAD

**Issue by rockphotog** [HL7Norway/basisprofiler-r3#12]
Skal vi mappe OID 7311 "PST Postadresse for organisasjoner" til STU3 "postal" i stedet for "work"? Mulig det er jeg som gjorde gal mapping.

**Comment by rockphotog** [comment]
Vi kan også mappe 3401 "BAD Ubrukelig adresse" til "old", da HL7 gjør det samme mellom v3 og STU3.

**Comment by kennethmyhra** [comment]
Enig i bruk av old, spesifikasjonen beskriver samme bruk.

Forvekslet use med type på work/postal?

**Comment by rockphotog** [comment]
Ja, forvekslet litt - vi bør splitte litt i mapping-tabellen for å vise at det er snakk om kodeverk for både type og use fra de tidligere kodeverkene. 

EDIT: Så OID 7311 "PST Postadresse for organisasjoner" skal mappes til "use=work" og type="postal|both", kanskje bare forvirrende. Jeg trekker det første forslaget, men tabellen bør justeres.

**Comment by kennethmyhra** [comment]
Mener den burde mappes til use=work og type=postal, men mulig jeg mangler noe historikk som tilsier at both skulle gi mening? I forhold til beskrivelsen "Postadresse for organisasjoner" gir det ikke helt mening.

**Comment by rockphotog** [comment]
Both: Bare hvis man hadde forutsetningen til å mappe to eksisterende kodete oppføringer for hhv bedriftsbesøksadresse og bedriftspostadresse som var samme adresse, men use case og sannsynlighet er vel smal.

**Comment by thomiz** [comment]
Da har jeg sett på innspillene deres og kommet med et helt annet forslag. Fint om dere ser igjennom. Selv synes jeg dette var et helt glimrende forslag: 
https://simplifier.net/guide/Basisprofilerno-basis/no-basis-Address

Tabellen fra forrige versjon:
![image](https://user-images.githubusercontent.com/6229665/45682129-ba6f7300-bb3f-11e8-94dc-38971a974f25.png)

**Comment by thomiz** [comment]
Markdown tabellen funker ikke :-(

**Comment by rockphotog** [comment]
HTML FTW

**Comment by thomiz** [comment]
@rockphotog Gidder ikke skrive om markdown tabellen i IG'en til HTML bare fordi denne issuetrackeren ikke håndterer Markdown tabeller slik det står i dokumentasjonen...

Men jeg hører du har mye fritid @rockphotog ?

**Comment by rockphotog** [comment]
https://www.tablesgenerator.com/html_tables

**Comment by thomiz** [comment]
Jeg har som sagt allerede en tabell, så jeg trenger ikke en til på et annet format :-) Men du må gjerne formater om hvis du vil @rockphotog

**Comment by kennethmyhra** [comment]
@thomiz Forslaget ditt ser bra ut, ingenting å tillegge fra denne kanten.

**Comment by thomiz** [comment]
Endringer er nå implementert basert på innspillene under høringen.
