### ISSUE TITLE
Simplifier: The resource cannot be rendered

### ISSUE THREAD

**Issue by rockphotog** [HL7Norway/basisprofiler-r3#14]
Gjelder implementasjonsguiden: https://simplifier.net/hl7norwayno-basis/basisprofilerno-basis

**Comment by thomiz** [comment]
Dette er en feature, ikke en bug. Dvs SIMPLIFIER rendrer ikke ImplementationGuide ressurser. Skal se om jeg kan legge inn en narrative så det ikke ser så stygt ut?

**Comment by thomiz** [comment]
Det er forresten en autogenerert fil fra SIMPLIFIER, så denne kan vi ikke fikse på. Feature request til Firely?
