### ISSUE TITLE
urn:uri burde bli byttet med urn:oid

### ISSUE THREAD

**Issue by gautebrakstad** [HL7Norway/basisprofiler-r3#15]
Ser en del oid's til volven er registrert med urn:uri:{oid}. Dette bør bli rettet til urn:oid:{oid} 
Eksempel urn:uri:2.16.578.1.12.4.1.1.3402  som er kommunenummer burde bli urn:oid:2.16.578.1.12.4.1.1.3402. Se https://tools.ietf.org/html/rfc3061

**Comment by thomiz** [comment]
Huff, dette er en bug. Skal fikse det.
Takk for beskjed!

**Comment by thomiz** [comment]
Dette er fikset, det var en skrivefeil i dokumentasjonen av noen elementer:
no-basis-bydelsnummer.namingsystem
no-basis-Patient.structuredefinition-profile
no-basis-Practitioner.structuredefinition-profile
no-basis-propertyinformation.structuredefinition-extension
no-basis-urban-district.structuredefinition-extension
