### ISSUE TITLE
Feil i url i no-basis-HumanName

### ISSUE THREAD

**Issue by micer2004** [HL7Norway/basisprofiler-r3#16]
Feil format på URL...
Er:
<url value="ttp://ehelse.no/fhir/StructureDefinition/no-basis-HumanName" />

Skal være:
<url value="http://ehelse.no/fhir/StructureDefinition/no-basis-HumanName" />

**Comment by rockphotog** [comment]
Her må du utdype litt...

**Comment by thomiz** [comment]
Fixed the bug
