### ISSUE TITLE
Extensions må følge navnestandard (certainty, sourceOfInformation)

### ISSUE THREAD

**Issue by rockphotog** [HL7Norway/basisprofiler-r3#17]
Det betyr liten forbokstav. Ser dog at disse ikke ligger i wiki'en, så jeg lager en egen issue for det.

**Comment by rockphotog** [comment]
https://github.com/HL7Norway/basisprofiler-r3/blob/emergingprofiles/StructureDefinition/no-basis-SourceOfInformation.StructureDefinition.xml

https://github.com/HL7Norway/basisprofiler-r3/blob/emergingprofiles/StructureDefinition/no-basis-Certainty.StructureDefinition.xml

**Comment by thomiz** [comment]
De nye profilene på medicatoin følger ikke navnestandard. Mangler dessuten noe på filnavn -extension og -profile for eksempel.

**Comment by rockphotog** [comment]
Disse to extensions er nå under revisjon da vi løfter Kjernejournal/Kritisk info til R4 og basisprofiler. SourceOfInformation ender trolig inn i Asserter (ref->healthcarePersonnel|Patient|etc.). Vi jobber med å lage en kj-AllergyIntolerance som skal erstatte kjki-Legemiddelreaksjoner og kjki-AndreReaksjoner (profilnavn tatt etter husk). 

Forslag: Vi lar saken stå og gjør ikke noe med den før vi har jobbet videre med KJ, og lukker den når arbeidet er ferdig.

**Comment by rockphotog** [comment]
Jobber nå med KJ, lukker denne. Det blir helt nye R4-profiler for Kjernejournal/Kritisk info.
