### ISSUE TITLE
Gjennomgang av diff ifht R4

### ISSUE THREAD

**Issue by oaassv** [HL7Norway/basisprofiler-r3#20]
Ta en gjennomgang for å sikre best mulig kompabilitet med R4. Det inkluderer å ta ut Medication.isBrand.

**Comment by rockphotog** [comment]
Jeg foreslår at dette gjøres i det vi flytter til R4, uten at vi forandrer på STU3-profilene. Enig, @oaassv ?

**Comment by oaassv** [comment]
Enig.

**Comment by rockphotog** [comment]
Lukkes, gjøres som en del av arbeidet.
