### ISSUE TITLE
Etablere videre prosess for nasjonale profiler (rikere enn basisprofilene) for medikasjon

### ISSUE THREAD

**Issue by oaassv** [HL7Norway/basisprofiler-r3#21]
Det ser ut til å være et behov for å gi rikere nasjonale føringer en  del områder som ikke nødvendigvis hører hjemme i basisprofilene. Det må gjøres en vurdering av hva som skal med i basisprofil, og hva som skal være med i nasjonale profiler på et mer spesifikt nivå. MedicationStatement.dosage er en kandidat for spesifisering i mer spesifikke nasjonale profiler.

**Comment by rockphotog** [comment]
Kan vurderer å flytte denne issuen til «best practice».

**Comment by rockphotog** [comment]
Lukker denne. Blir ivaretatt andre steder.
