### ISSUE TITLE
Legge til rette for packages-releasen for basisprofil-IG

### ISSUE THREAD

**Issue by rockphotog** [HL7Norway/basisprofiler-r3#25]
Legge til rette for packages basert på NPM. Dette arbeidet er ikke ferdig og kommer nok ikke i R4 heller, men det er en del prinsipper som vi kan se på allerede nå når det kommer til versjonering etc. Eksempel er navn på pakker, som kan være type «hl7.fhir.no.basis : 1.0.0 (versjon)» eller noko. 

http://wiki.hl7.org/index.php?title=FHIR_NPM_Package_Spec

**Comment by thomiz** [comment]
Hmm, foreslår du egentlig å skrote namespacet vi valgte på forrige workshop?
Da valgte vi å gå videre med hl7.no/fhir

Tyskerne og Nederlenderne bruker:
fhir.de
fhir.nl

Det skal vel antakelig være samsvar mellom navnene i NPM pakkene og canonical url?

**Comment by rockphotog** [comment]
Tror det vil være to forskjellige ting, men uansett så er dette package-greiene ikke ferdige, så vi kan skynder oss sakte = planlegge.

**Comment by rockphotog** [comment]
Simplifier har nå en beta for packages:
https://simplifier.net/HL7Norwayno-basis/~packages

**Comment by rockphotog** [comment]
Jeg lukker denne, @thomiz har testet litt - så ser vi videre på dette i R4.
