### ISSUE TITLE
Patient.urbanDistrict (Kardinalitet og plassering av extension)

### ISSUE THREAD

**Issue by kennethmyhra** [HL7Norway/basisprofiler-r3#26]
Er det riktig at kardinaliteten til Patient.urbanDistrict er 0..*, burde det ikke være 0..1?

Plasseringen av extension urbanDistrict. I dag ligger den rett på Patient, hadde det ikke vært mer naturlig at denne var en del av Address?

**Comment by thomiz** [comment]
Mulig det bare er en bydel ja, og ideelt sett skulle urbanDistrict vært knyttet til en adresse. Jeg er usikker på om dette faktisk er adresseinformasjon. Tror hverken matrikkelen eller Folkeregisteret har dette som del av adresse, matrikkelen har en hel del annen kretsinformasjon i tilknytning til adresse ser jeg, men jeg ser ikke bydel nevnt eksplisitt.

**Comment by thomiz** [comment]
Vi satser på å rette opp dette i migreringen til R4. 
Endringer: 
Flytte urbanDistrict til Address
Endre kardinalitet på urbanDistrict til 0..1

**Comment by rockphotog** [comment]
Løses i R4.
