### ISSUE TITLE
no-basis-Address legge til matrikkeladresse?

### ISSUE THREAD

**Issue by thomiz** [HL7Norway/basisprofiler-r3#29]
Vi har idag eiendomsinformasjon som kan benyttes til å lagre informasjon om eiendommen der det ikke finnes entydige gateadresser. Folkeregisteret opererer med et begrep som kalle "matrikkeladresse" som er eiendomsinformasjon men uten seksjonsnummer men istedenfor et undernummer for å skille flere adresser på samme bruks/gårdsnummer. Det er en konstruksjon i folkeregisteret og bør kanskje også representeres i no-basis-Address enten istedenfor eiendomsinformasjon eller i tillegg til denne.

**Comment by rockphotog** [comment]
Vil det holde at denne ligge i profilen for Grunndata?

**Comment by rockphotog** [comment]
Oppfølging: Spørre spesialist/AMK om de benytter matrikkeladresse fra PREG.

**Comment by rockphotog** [comment]
Vi dekker det PREG kan levere i dag i basis (extension for eindomsinformasjon).
