### ISSUE TITLE
Felles hjelpenummer

### ISSUE THREAD

**Issue by rockphotog** [HL7Norway/basisprofiler-r3#3]
Mangler beskrivelse :-)

**Comment by thomiz** [comment]
no-basis-Patient.identifier
FNR har beskrivelsen :-)
 
"Felles hjelpenummer for the patient. Felles hjelpenummer as one of the possible patient identification numbers. The norwegian Felles hjelpenummer shoud only be used when the Fødselsnummer og D-number is unknown."

**Comment by rockphotog** [comment]
Replace with TODO
https://simplifier.net/HL7Norwayno-basis/2.16.578.1.12.4.1.4.3/~xml 

:-)

**Comment by rockphotog** [comment]
Skjønner ikke hvordan jeg kan lage en branch basert på en issue.

**Comment by thomiz** [comment]
Da er det fikset i Git'en

**Comment by thomiz** [comment]
Og automatisk oppdatert på SIMPLIFIER, jeg kan bli vant til dette :-)
