### ISSUE TITLE
Får feilmelding i Forge på de norske profilene

### ISSUE THREAD

**Issue by ellgre** [HL7Norway/basisprofiler-r3#31]
Jeg har lastet ned alle filer fra siden https://simplifier.net/hl7norwayno-basis og får følgende feil når jeg prøver å åpne profilene i Forge: "_Unable to resolve reference to profile 'http://hl7.no/fhir/StructureDefinition/no-basis-Person_'". Det samme gjelder også for Practitioner og HumanName. Jeg får åpnet extensions.

Jeg har også hentet ned filene fra grunndata sin github, og får de samme feilmeldingene med de profilene også.

Er det noe spesielt jeg må gjøre for å kunne åpne disse profilene i Forge?

**Comment by thomiz** [comment]
Beklager litt sent svar. Det er enklere å laste ned prosjektet direkte fra GitHub, da får du i utgangspunktet alle filene i pakken ned som en pakke med riktig filstruktur. Hvis man gjør det via SIMPLIFIER har man mange valg for nedlasting blant annet JSON, og filene struktureres litt forskjellig etter hva man velger. Hvilket av valgene har du benyttet?

Når har jeg forsøkt flere av nedlastingsvalgene fra SIMPLIFIER men har ingen problemer med å åpne filene i Forge. Så lurer litt på hva som går galt her.

**Comment by ellgre** [comment]
Kan det være at jeg mangler noen lesetilganger? Når jeg prøver linken som står som "Canonical" http://hl7.no/fhir/StructureDefinition/no-basis-Practitioner får jeg feilmelding "404 - Kategorien ble ikke funnet".

Jeg har prøvd å laste ned både som json og som xml og får samme problem med begge.

**Comment by vadi2** [comment]
If you use "Canonical", paste it in https://simplifier.net/resolve.

**Comment by ellgre** [comment]
Men hvorfor får jeg feilmelding på denne linken fra Forge?

**Comment by vadi2** [comment]
Download that profile and put it into the same folder so Forge can find it.

**Comment by ellgre** [comment]
Da fungerte det. Tusen takk for hjelpen.
