### ISSUE TITLE
Arkivere basisprofiler-r3

### ISSUE THREAD

**Issue by rockphotog** [HL7Norway/basisprofiler-r3#32]
Skal vi arkivere dette repoet, @thomiz @oaassv @HL7Norway/tsk ? 

Er det noen som bruker STU3 basisprofiler som eventuelt kan forvalte det videre?

https://help.github.com/en/github/creating-cloning-and-archiving-repositories/about-archiving-repositories

**Comment by thomiz** [comment]
VKP STU3 baserer seg på no-basis STU3. 
De er for sikkerhetsskyld i drift. Bør derfor være sikker på at de har migrert før vi arkiverer dette.

**Comment by rockphotog** [comment]
Utsatt.
