### ISSUE TITLE
Adresse-format og extensions

### ISSUE THREAD

**Issue by micer2004** [HL7Norway/basisprofiler-r3#4]
I HL7-møte på Gardermoen hadde jeg foreslått at vi bygger på nederlandsk core-adresse som benytter seg av extension på line-elementet

![image](https://user-images.githubusercontent.com/14926615/44528100-00741b00-a6e9-11e8-97c5-815ed99c41ea.png)

Til venstre er det nederlandsk, til høyere norsk... Finn forskjeller i strukturen ;) ... Kunne vi holde oss til bare et språk på basis profiler, dvs. ingen norsk, ref. "eiendomsinformasjon"?

**Comment by torilorm** [comment]
Inneholder den nederlandske extension informasjon om gards/bruksnummer? Særnorske betegnelser som dette, mener jeg er en fordel å holde på norsk for at de som bruker det skal skjønne hva det er, samme med kommune. Man kan heller legge til en kommentar på elementene på engelsk som beskriver hva dette er til f.eks utenlandske leverandører eller andre som vil ta i bruk den norske profilen. "Eiendomsinformasjon" kan godt være "propertyinfo" eller lign på engelsk, mens altså betegnelser som er veldig spesifikt for norge bør holdes på norsk.

**Comment by micer2004** [comment]
Jeg er ingen ekspert på geografiske betegnelser i Norge og deres engelske ekvivalenter men tenker at hvis man henvender seg til f.eks. Kartverket så kan vi få de korrekte engelske oversettelser. P.t. må jeg forholde meg til API'er som er litt engelsk og litt norsk og ut av erfaring kan jeg bekrefte at det kan skape litt kaos i koden. Det er sikkert flere termer som stammer fra andre sektorer og min anbefaling er bare å holde oss til samme språk på felles basis profiler så lenge det går...

**Comment by rockphotog** [comment]
@thomiz Kan du sjekke om det finnes en offisiell oversettelse til engelsk - du sitter vel sammen med noen kart/geofolk i Standardiseringsrådet?

**Comment by thomiz** [comment]
Det finnes offisielle oversettinger av disse termene. Så vi kan benytte disse, selv om nordmenn nok ikke kjenner til disse. Fra kartverket.no

Cadastral unit
All properties in Norway have a set of numbers that identifies the property unit in the land register and cadastre.

Kommunenummer = 
Municipality number

Gårdsnummer = 
Cadastral unit number

Bruksnummer = 
Property unit number

Festenummer = 
Leasehold number

Seksjonsnummer = 
Condominium unit number

**Comment by thomiz** [comment]
Jeg har gjort en oppdatering av dokumentasjonen for å i større grad gå bort fra norske termer. Se implementasjonsguiden:
https://simplifier.net/guide/basisprofilerno-basis/introduction

**Comment by thomiz** [comment]
Vi må ha en diskusjon på om vi skal extende line elementet slik nederlendernde og tyskerne gjør.

**Comment by rockphotog** [comment]
Hvis det er aktuelt å gjenbruke eiendomsinformasjon et annet sted enn i adresse bør det være en egen extension, men det er kanskje ikke så sannsynlig?

**Comment by oaassv** [comment]
Det vanlige i Norge er vel at vi strukturerer input i navn, adresselinje, postnummer, poststed (dette dekkes av profilen). Hvor stort er behovet for å si noe mer enn linje 1, linje 2 på adresselinje - det vil si å strukturere gatenummer, eventuelt postboks i egne felter? Er dette noe folkeregisteret gjør?

**Comment by rockphotog** [comment]
Brukes postboks blir det en egen adresseinstans merket "postal", og evt besøksadresse "physical". Vi hindrer uansett ingen å bruke to eller flere linjer i basisprofilene.

**Comment by thomiz** [comment]
> Hvis det er aktuelt å gjenbruke eiendomsinformasjon et annet sted enn i adresse bør det være en egen extension, men det er kanskje ikke så sannsynlig?

Det er slik det byggd opp: no-basis-propertyinformation er egen extension som benyttes i no-basis-address.

**Comment by thomiz** [comment]
Lukkes etter endring til engelsk for eiendomsinformasjon. Behovet for koding av informasjon i adress.line er ikke synliggjort.

**Comment by oaassv** [comment]
Hei,
jeg ser denne er blitt oversatt og lukket. I diskusjonen knyttet til oversettelse er det uttrykt argumentasjon for å beholde dette på norsk, noe jeg i dette tilfellet vil si meg enig i. Gårdsnummer, seksjonsnummer etc oppfatter jeg som spesifikke og særnorske begreper som det gir liten hensikt å oversette. Begrepene vil virke fremmede for bruker, og selv om det finnes oversettelser til engelsk så tror jeg det uansett ikke vil være noen garanti for at verdiene faktisk kan utveksles på tvers av landegrenser - på grunn av ulik kontekst og bruk. Jeg støtter derfor Torils forslag om at Eiendomsinformasjon godt kan være på engelsk, men at det er mer brukervennlig å beholde de mer spesifikke termene på norsk.  Noen andre argumenter for eller imot?

**Comment by rockphotog** [comment]
Termer må uansett være med både på norsk og engelsk. Spørsmålet blir da om hva som skal ligge som attributt-navn, og hva som skal ligge i beskrivelsen av attributtet. Så lenge de klart kommer frem i dokumentasjonen hva slags norske begreper dette er, kan attributtene godt ha engelske termer der offisielle oversettelser finnes. Som diskutert tidligere synes jeg det er et godt prinsipp for basisprofilene.

**Comment by rockphotog** [comment]
Hvis ingen protesterer (_absence of sustained opposition_), foreslår jeg at vi lukker denne på fredag 19.10.2018 og beholder engelske navn (siden det finnes offisielle norske oversettelser). Dette basert på [prinsipper vi har diskutert](https://github.com/HL7Norway/best-practice/wiki/Prinsipper-for-basisprofiler), men som i seg selv ikke er vedtatt av noen.

**Comment by thomiz** [comment]
Lukket etter bortfall av motstand :-)
