### ISSUE TITLE
Ta høyde for nytt personnummer

### ISSUE THREAD

**Issue by torilorm** [HL7Norway/basisprofiler-r3#5]
Det vil komme nytt personnummer de neste årene. Dette vil gjelde for nyfødte, men de norske profilene bør ta høyde for dette allerede nå, dersom det er mulig.

Jeg finner ikke noe informasjon om hva som er bestemt, men her er høringsnotat omkring dette fra 2017:
https://www.regjeringen.no/contentassets/c7cc56174c6645349b847c0614119e8b/h_notat_ene_personidentifikator.pdf

**Comment by rockphotog** [comment]
Forslaget er 1B, der ett kontrollsiffer gjøres om til "tellenummer"/individet, så det blir fortsatt 11 sifre som i dag. Vi har vel ingen constraints i profilen nå (i Patient.identifier:FNR.value).

**Comment by rockphotog** [comment]
Da lukker jeg denne på grunnlag av diskusjon i TSK.
