### ISSUE TITLE
Ta høyde for ny helse-id for helsepersonell og andre ansatte i spesialisthelsetjenesten

### ISSUE THREAD

**Issue by torilorm** [HL7Norway/basisprofiler-r3#6]
Dette er kanskje ikke mulig å ta høyde for nå, men det kommer en ny helse-id for helsepersonell og ansatte i spesialisthelsetjenesten, denne bør vi få inn så fort det er bestemt hvordan denne id-en blir.

**Comment by rockphotog** [comment]
Interessant - har du noen informasjon om denne? Det har jo vært etterlyst en løsning for alle i sektoren, der også kommunene nå kommer med ansatte som skal samhandle, men som mangler HPR-nummer.

**Comment by torilorm** [comment]
Jeg skal på et møte i morgen om hvordan Helse Vest skal ta i bruk dette, da får jeg nok vite mer. Mulig jeg skal sitte i dette prosjektet videre så da kan jeg holde dere informert.

**Comment by rockphotog** [comment]
Da lukker jeg denne på grunnlag av diskusjon i TSK.
