### ISSUE TITLE
Skrive noe om bruk av HER-id i Organization

### ISSUE THREAD

**Issue by thomiz** [HL7Norway/basisprofiler-r3#7]
Siste oppdatering av no-basis-Organization er HER-id slicen tatt bort. Vi må beskrive hvordan HER-id skal benyttes i FHIR ressursene. Spesielt hvis man skal adressere ved hjelp av Tjenestebasert adressering ved bruk av FHIR Mesaging.

**Comment by thomiz** [comment]
Se her @rockphotog  og @oaassv . Forslag til modell for no-basis-MessageHeader med bruk av HealthcareService istedenfor Practitioner og Organization som adresserings endepunkt.
https://simplifier.net/guide/Basisprofilerno-basis/Servicebasedmessageaddressing

**Comment by rockphotog** [comment]
Så det konkrete forslaget er en utvidelse av hvem som kan refereres fra sender/receiver. 

I dag: sender/receiver | Σ | 0..1 | Reference(Practitioner|Organization)
Ønsket: sender/receiver | Σ | 0..1 | Reference(Practitioner|Organization|HealthcareService) 

EDIT: Er dette mulig å profilere @thomiz ?

**Comment by thomiz** [comment]
@rockphotog ja, det er mulig å profilere, vi har forsåvidt allerede gjort det i vkp sammenheng:
https://simplifier.net/guide/Velferdsteknologiskknutepunkt2/vkp-MessageHeader

**Comment by thomiz** [comment]
Et bedre forslag er kanskje å bare godta:
no-basis-HealthcareService og HealthcareService i no-basis-MessageHeader og vkp-MessageHeader

Men det er kanskje litt strengt for en basisprofil?

**Comment by rockphotog** [comment]
Du tenkte på å utelate Organization og Practitioner i Sender/Receiver i basisprofil? Det er nok litt strengt, men vi kan gjøre det i en no-MessageHeader ("nasjonal profil") som kan være del av en implementasjonsguide for messaging mellom virksomheter.

**Comment by rockphotog** [comment]
Jeg har nå opprettet et «FHIR Messaging»-prosjekt under best practice, så kan vi samle alle TODOs der. Direktoratet for e-helse har dette et stykke ut på sitt veikart (når det blir godkjent), men jeg tror det er andre som har behov for best practice og basisprofiler knyttet til FHIR Messaging som kan støtte tjenestebasert adressering.

**Comment by rockphotog** [comment]
Er dette en issue vi kan lukke @thomiz ?

**Comment by rockphotog** [comment]
Lukkes.
