### ISSUE TITLE
Hvordan skal fylke registreres i adresse-sammenheng?

### ISSUE THREAD

**Issue by micer2004** [HL7Norway/basisprofiler-r3#9]
Skal vi benytte County ref. diskusjon tidligere? Eller skal det lages eget extension?

**Comment by thomiz** [comment]
Nei, det skal ikke lages egen extension, vi var enige på workshop'en om at vi skulle definere det inn i eksisterende Address ressurs. Fylke skal legges inn i "state" elementet i no-basis-Address. Se dokumentasjon her: https://simplifier.net/hl7norwayno-basis/no-basis-address
